//
// UIColor+EHIColor.m 
// This file is generated by Spectra, so don't expect to make any persistent changes
//

@implementation UIColor (EHIColor)

+ (UIColor *)ehi_greenColor
{
    return [UIColor colorWithRed:0.09f green:0.60f blue:0.35f alpha:1.00f];
}

+ (UIColor *)ehi_darkGreenColor
{
    return [UIColor colorWithRed:0.05f green:0.43f blue:0.25f alpha:1.00f];
}

+ (UIColor *)ehi_mediumGreenColor
{
    return [UIColor colorWithRed:0.02f green:0.55f blue:0.32f alpha:1.00f];
}

+ (UIColor *)ehi_lightGreenColor
{
    return [UIColor colorWithRed:0.00f green:0.73f blue:0.44f alpha:1.00f];
}

+ (UIColor *)ehi_redColor
{
    return [UIColor colorWithRed:0.88f green:0.07f blue:0.07f alpha:1.00f];
}

+ (UIColor *)ehi_tanColor
{
    return [UIColor colorWithRed:0.95f green:0.92f blue:0.85f alpha:1.00f];
}

+ (UIColor *)ehi_silverColor
{
    return [UIColor colorWithRed:0.59f green:0.59f blue:0.59f alpha:1.00f];
}

+ (UIColor *)ehi_goldColor
{
    return [UIColor colorWithRed:0.81f green:0.72f blue:0.49f alpha:1.00f];
}

+ (UIColor *)ehi_blackColor
{
    return [UIColor colorWithRed:0.07f green:0.05f blue:0.05f alpha:1.00f];
}

+ (UIColor *)ehi_grayColor0
{
    return [UIColor colorWithRed:0.96f green:0.96f blue:0.96f alpha:1.00f];
}

+ (UIColor *)ehi_grayColor1
{
    return [UIColor colorWithRed:0.89f green:0.89f blue:0.89f alpha:1.00f];
}

+ (UIColor *)ehi_grayColor2
{
    return [UIColor colorWithRed:0.84f green:0.84f blue:0.84f alpha:1.00f];
}

+ (UIColor *)ehi_grayColor3
{
    return [UIColor colorWithRed:0.67f green:0.67f blue:0.67f alpha:1.00f];
}

+ (UIColor *)ehi_grayColor4
{
    return [UIColor colorWithRed:0.27f green:0.30f blue:0.29f alpha:1.00f];
}

+ (UIColor *)ehi_grayColor5
{
    return [UIColor colorWithRed:0.76f green:0.76f blue:0.76f alpha:1.00f];
}

+ (UIColor *)ehi_grayColor6
{
    return [UIColor colorWithRed:0.50f green:0.50f blue:0.50f alpha:1.00f];
}

+ (UIColor *)ehi_yellowSpecialColor
{
    return [UIColor colorWithRed:0.95f green:0.83f blue:0.00f alpha:1.00f];
}

+ (UIColor *)ehi_yellowWarningColor
{
    return [UIColor colorWithRed:0.96f green:0.85f blue:0.16f alpha:1.00f];
}

+ (UIColor *)ehi_yellowWarningColor2
{
    return [UIColor colorWithRed:1.00f green:0.97f blue:0.79f alpha:1.00f];
}

+ (UIColor *)ehi_graySpecialColor
{
    return [UIColor colorWithRed:0.93f green:0.93f blue:0.93f alpha:1.00f];
}

+ (UIColor *)ehi_blackSpecialColor
{
    return [UIColor colorWithRed:0.00f green:0.00f blue:0.00f alpha:0.88f];
}

+ (UIColor *)ehi_blackSpecialColor2
{
    return [UIColor colorWithRed:0.09f green:0.10f blue:0.09f alpha:1.00f];
}

@end

