//
// UIColor+EHIColor.h 
// This file is generated by Spectra, so don't expect to make any persistent changes
//

@interface UIColor (EHIColor)

+ (UIColor *)ehi_greenColor;
+ (UIColor *)ehi_darkGreenColor;
+ (UIColor *)ehi_mediumGreenColor;
+ (UIColor *)ehi_lightGreenColor;
+ (UIColor *)ehi_redColor;
+ (UIColor *)ehi_tanColor;
+ (UIColor *)ehi_silverColor;
+ (UIColor *)ehi_goldColor;
+ (UIColor *)ehi_blackColor;
+ (UIColor *)ehi_grayColor0;
+ (UIColor *)ehi_grayColor1;
+ (UIColor *)ehi_grayColor2;
+ (UIColor *)ehi_grayColor3;
+ (UIColor *)ehi_grayColor4;
+ (UIColor *)ehi_grayColor5;
+ (UIColor *)ehi_grayColor6;
+ (UIColor *)ehi_yellowSpecialColor;
+ (UIColor *)ehi_yellowWarningColor;
+ (UIColor *)ehi_yellowWarningColor2;
+ (UIColor *)ehi_graySpecialColor;
+ (UIColor *)ehi_blackSpecialColor;
+ (UIColor *)ehi_blackSpecialColor2;

@end

