language: objective-c
osx_image: xcode9.3
branches:
  only:
  - master
  - develop
  - /^release.*$/
before_install:
- export SIMULATOR_UDID=`instruments -s devices | grep "iPhone SE (11.3" | awk -F '[ ]' '{print $4}' | awk -F '[\[]' '{print $2}' | sed 's/.$//'`
- open -a "simulator" --args -CurrentDeviceUDID $SIMULATOR_UDID & # warm up the simulator
before_script:
- ./scripts/configure_keychain.sh
- gem install bundler
- gem install xcpretty
script:
  - ./scripts/build.sh
  - ./scripts/test.sh
after_success:
- sleep 10 # https://github.com/travis-ci/travis-ci/issues/4725
- ./scripts/hockey_upload.sh
env:
  global:
  - APP_NAME="Enterprise"
  - XCODE_CONFIGURATION="UAT"
  - PROFILE_NAME="Enterprise"
  - CRITTERCISM_APP_ID="52fb93bc97c8f26539000004"
  - CRITTERCISM_API_KEY="f44b7917d02adccef68dee886b91686f"
  # KEY_PASSWORD
  - secure: "i6J6aBSOEPQIl7j/b27w5/Tj8LJjjTmYczz10TSzTm3/cAfzzSLXt7m5GbVCemRh5jhABqtXE7RXDR1pauKG4F5N6IQqSLq/BRF0on6Ubj1XGprPE8RtzNPbORTP+9bkexFhCSNbvP2cf+BiVFDJh9AbFw3xuovGjRB/rIgl+NXhtZjq+xfQvuZmNGTcWlw5OP3zRwTAawCsWzgZIo5u+59tNqVDaTC6T1dP6qWR3bMdR4QRoWK063Pyoj2RuNknwox9I6xbgQEf4E24y3g0pihIALLDgThOsTIXdiL3cTXiWzY2AGMc/pN1PBouqpguFUM9bOEimyb6iOu/Cg1Nn6/t2D7l7X/GUV9PtfLW+HxRh5xH5N+AqwTnu380etmOlv/sXkYDCLMTkCIQ2rbk8LtNqMayKtpCAiMa8mR62e5uMmYBT1rfKAcRbKZVtvU+F0ljBQHZZLhUCiXadAEFiR14ckyI1YQlRjhpMG9qqXYYR3iiXDuAPIzLtHr+A2PRvNf27W7SXVe2k3N2icI8ys+WT3hqAFlKQ7TabLpxZrHpAqe+96NEAaTavNDyoucpJcv/J5ZeBo/3Io9g2nNZQ7G2k+gXm5H6+T/O480dswLwMjhanJl4yY3N7lKqznnHabXTrZsRE5GS0w5x1AEQ/oCq9nNDWaA0Kkv9X+WQGOU="
  # HOCKEY_API_KEY
  - secure: "RO+9OoW8waoLSJEpANCLeSDtth9ocHOJKZgnAYAUDB6EJz5QU0YvQdZKrdGo2XCK0Eg0ZJZMqsN838trzSkosWsqpU7TMleI8ne/CGXdcgNYQF9kxF6tqlxO6fPaKV3bvyMCxUd9R81uxs6u2weskrcEizm109O0S44a7zTYH35euxiiW+Zks+GwtNXD12sI6TL10E3SHUWGHpP7B95gss56sujIeCGslmOoGCX1O/RseHvNwnMdjyQWTGMhR2DBiW3k3wUtOaDFbL5AfzP25ZRzky3qAcROzdgedgCCfnsyPzchoMw3srQw9DJiainfyKS4XSz+8cJr26muoYC8HFu1xgStO4Wa1lrDYqUTrwRjquVAO+0xHipXC+cxHpSYpEwGqW7OXDfkjvoLNlIDDpo3yQKZmu3GQiwYpR3ydBngJ+OJdOWN4t2losPTGiGHrFhesqnXtldhnP/ezvWTaI9Tqktqgw1BqRytPmI7mo04TJSp3tJW6nWTK6RWI657fUfINgXfZpeTVzu4BvDDxkpRBVZqCHSITxifwZuOBY6j4cOSqI2qq2Vpeq74uQEMs2oVC5Hwn+jNhheOQCm6t3Kca81PBquyPR7GNuMBggEFdft6ZLwS1lW9J3ugmBYiLXQ8dU/up5Cx8XhKT5396j6UWRIGIj1yP3t/fMexRb8="

notifications:
  slack: "isobar-us:pCKpgFvEFe9q3dcT9rZvxhOK"
