#!/bin/bash

generate_plist_keys () {
	json=$(echo $1 | sed 's/","/"\
		"/g')
	locale=$(echo $2 | tr '_' '-')
	plistValues=$'//\r// This file is generated by loadstrings.sh\r//\r// Add additional localized .plist strings by adding their keys\r// in loadstrings.sh\r//\r\r'

	# use en-GB as Base locale
	if [ "$locale" == "en-GB" ]
	then
		locale="Base"
	fi

	for plistKey in application_shortcut_start_reservation_title \
					application_shortcut_nearby_locations_title \
					location_services_always_usage_description \
					location_services_on_description \
					location_services_when_in_use_description \
					camera_service_description \
					photos_service_description \
					calendar_service_description 
	do
		# appropriate line
		found=$(echo "$json" | egrep -o "(\"$plistKey\" *):( *\".*?\")")

		# chop off key and trailing quote
		value=$(echo "$found" | cut -d: -f2 | xargs)

		# fix location permissions headers until content is updated
		if [ "$plistKey" = "location_services_always_usage_description" ]; then
			plistKey="NSLocationAlwaysUsageDescription"
		elif [ "$plistKey" = "location_services_on_description" ]; then
			plistKey="NSLocationAlwaysAndWhenInUseUsageDescription"
		elif [ "$plistKey" = "location_services_when_in_use_description" ]; then
			plistKey="NSLocationWhenInUseUsageDescription"
		elif [ "$plistKey" = "camera_service_description" ]; then
			plistKey="NSCameraUsageDescription"
		elif [ "$plistKey" = "photos_service_description" ]; then
			plistKey="NSPhotoLibraryUsageDescription"
		elif [ "$plistKey" = "calendar_service_description" ]; then
			plistKey="NSCalendarsUsageDescription"
		fi

		plistValues+="\"$plistKey\"=\"$value\";"
		plistValues+=$'\r'
	done

	echo $plistValues > Enterprise/Resources/${locale}.lproj/InfoPlist.strings
}

for locale in en_US en_CA en_GB es_US es_ES fr_CA fr_FR de_DE
do
	json=$(curl https://api-xqa.nonprod.gcs.ehi.com/bin/mobile-app.enterprise.${locale}.json?cachebust=aaa)

	echo "$json" | tr -d '\n' > Enterprise/Localizations/localizable.${locale}.json

	# write plist specific localized keys to .strings files
	generate_plist_keys "$json" $locale
done
cp Enterprise/Localizations/localizable.en_GB.json Enterprise/Localizations/localizable.en.json
cp Enterprise/Localizations/localizable.es_ES.json Enterprise/Localizations/localizable.es.json
cp Enterprise/Localizations/localizable.fr_FR.json Enterprise/Localizations/localizable.fr.json
cp Enterprise/Localizations/localizable.de_DE.json Enterprise/Localizations/localizable.de.json
