platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'

# allow cocoapods to mirror our custom 'Tets' configuration
project 'Enterprise', 'Tests' => :debug

def shared_pods
    # architectural dependencies
    pod 'Masonry', '1.1.0'
    pod 'CocoaLumberjack', '1.9.2'
    pod 'AFNetworking', '3.1.0'
    pod 'YOLOKit', '11.2.0'
    pod 'libPhoneNumber-iOS', '0.9.13'

    # reporting dependencies
    pod 'CrittercismSDK', '5.8.0'
    pod 'Localytics', '5.1.0'
    pod 'CardIO', '5.4.1'
    pod 'ForeSee', '5.0.3'
    pod 'Appsee', '2.4.1'

    # React Native
    # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

end

target 'Enterprise' do
    shared_pods
end

target 'EnterpriseTests' do
    pod 'Specta', '1.0.7'
    pod 'Expecta', '1.0.6'
    pod 'OCMockito', '5.1.0'
    pod 'OCHamcrest', '7.1.0'
    pod 'YOLOKit', '11.2.0'
end

target 'EnterpriseWatchExtension' do
    platform :watchos, '2.0'
    pod 'YOLOKit', '11.2.0'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
            config.build_settings['CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF'] = 'NO'
            config.build_settings['CLANG_WARN_STRICT_PROTOTYPES'] = 'NO'
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        end
    end
end
