//
//  EHIAccessibilityIdentifiers.h
//  Enterprise
//
//  Created by Rafael Ramos on 6/30/16.
//  Copyright © 2016 Enterprise. All rights reserved.
//

#define EHIDashboardSearchInputKey              @"dashboard_search_locations_area"
#define EHILocationsSearchInputKey              @"search_input"
#define EHILocationsSelectLocationKey           @"right_container"
#define EHIItinerarySelectPickupDateKey         @"select_pickup_date_view"
#define EHIItinerarySelectReturnDateKey         @"select_return_date_view"
#define EHIItineraryAddContractKey              @"add_cid_button"
#define EHIItineraryContractKey                 @"cid_edit_text"
#define EHIItineraryCalendarViewKey             @"calendar_grid"
#define EHIItineraryCalendarTimeKey             @"select_time_button"
#define EHIItineraryContinueKey                 @"button_continue"
#define EHIReservationFlowContinueKey           @"continue_button"
#define EHIReservationFlowBookKey               @"book_rental_button"
#define EHIClassSelectCarPriceKey               @"price_container"
#define EHIClassSelectCarTotalPriceKey          @"class_price"
#define EHIClassSelectCarTitleKey               @"class_title"
#define EHIClassSelectCarSubtitleKey            @"class_description"
#define EHIConfirmationNumberKey                @"confirmation_number_text_view"
#define EHIConfirmationModifyKey                @"modify_reservation_button"
#define EHIConfirmationReturnDashboardKey       @"return_to_dashboard_button"
#define EHIConfirmationCancelKey                @"cancel_reservation_button"
#define EHIConfirmationPaymentMethodKey         @"payment_method"
#define EHIConfirmationPaymentDetailsKey        @"payment_method_details"
#define EHIReservationDiscountNameKey           @"contract_name"
#define EHIMenuRowKey                           @"navigation_linear_layout"
#define EHIMyRentalsLookUpKey                   @"button"
#define EHILookupRentalConfirmationKey          @"confirmation_number_input"
#define EHILookupRentalFirstNameKey             @"first_name_input"
#define EHILookupRentalLastNameKey              @"last_name_input"
#define EHILookupRentalFindRentalKey            @"find_rental_button"
#define EHIReviewAddedExtrasEmptyKey            @"no_extras_added_item"
#define EHIReviewAddedExtrasRowKey              @"added_extras_container"
#define EHIReviewCarClassKey                    @"review_car_class_view"
#define EHIReviewCarClassTypeKey                @"car_class_type"
#define EHIReviewCarClassNameKey                @"car_name"
#define EHIReviewDriverInfoNameKey              @"driver_name_view"
#define EHIReviewDriverInfoEmailKey             @"driver_email_view"
#define EHIReviewDriverInfoPhoneKey             @"driver_phone_view"
#define EHIExtrasExtraRowKey                    @"extra_item_view"
#define EHIExtrasExtraTitleKey                  @"extra_title"
#define EHIExtrasExtraSubtitleKey               @"extra_subtitle"
#define EHIExtrasExtraToggleKey                 @"check_box"
#define EHIDriverInfoFirstNameKey               @"first_name"
#define EHIDriverInfoLastNameKey                @"last_name"
#define EHIDriverInfoPhoneNumberKey             @"phone_number"
#define EHIDriverInfoEmailKey                   @"email"
