//
//  EHIViewControllers.h
//  Enterprise
//
//  Created by Ty Cobb on 1/9/15.
//  Copyright (c) 2015 Enterprise. All rights reserved.
//

#define EHIScreenRNTest                  @"RN-test-screen"

#define EHIScreenLocations               @"locations"
#define EHIScreenLocationDetails         @"location"
#define EHIScreenLocationsMap            @"map"
#define EHIScreenLocationsList           @"map-list"
#define EHIScreenLocationWayfinding      @"wayfinding"
#define EHIScreenLocationFilter          @"location-filter"
#define EHIScreenLocationSearchNoResult  @"location-search-no-result-modal"
#define EHIScreenSingleDateSelect 		 @"single-date-select"
#define EHIScreenSingleTimeSelect        @"single-time-select"

#define EHIScreenPolicies                @"policies"
#define EHIScreenPolicyDetail            @"policy"

#define EHIScreenMainSignin                     @"main-signin"
#define EHIScreenSignin                         @"signin"
#define EHIScreenSigninEmerald                  @"signin-emerald"
#define EHIScreenSigninRecovery                 @"signin-recovery"
#define EHIScreenForgotPassword                 @"forgot-password"
#define EHIScreenEnrollmentStepOne              @"enrollment-step-one"
#define EHIScreenEnrollmentStepTwo              @"enrollment-step-two"
#define EHIScreenEnrollmentStepThree            @"enrollment-step-three"
#define EHIScreenEnrollmentConfirmation         @"enrollment-step-confirmation"
#define EHIScreenEnrollmentIssues               @"enrollment-issues"
#define EHIScreenConfirmation                   @"confirmation"
#define EHIScreenTerms                          @"terms"
#define EHIScreenTermsAndConditions             @"terms-conditions"
#define EHIScreenSurvey       					@"survey-accepted"
#define EHIScreenSurveyInvite                   @"survey-invite"
#define EHIScreenConfirmationCancelReservation  @"confirmation-cancel-reservation"

#define EHIScreenWebView            @"web-view"
#define EHIScreenWebBrowser         @"web-browser"
#define EHIScreenInfoModal          @"info-modal"
#define EHIScreenCallSupport        @"call-support"

#define EHIScreenMenu                   @"menu"
#define EHIScreenDashboard              @"dashboard"
#define EHIScreenSettings               @"settings"
#define EHIScreenSettingsNotifications  @"settings-notifications"
#define EHIScreenCustomerSupport        @"customer-support"
#define EHIScreenOnboarding             @"onboarding"

#define EHIScreenRentals            @"rentals"
#define EHIScreenRentalLookup       @"rental-lookup"
#define EHIScreenExtendRental       @"extend-rental"

#define EHIScreenInvoiceDetails     @"invoice"

#define EHIScreenRewardsBenefitsAuth @"rewards-benefits"
#define EHIScreenRewardsLearnMore    @"learn-more"
#define EHIScreenAboutEnterprisePlus @"about-enterprise-plus"
#define EHIScreenRewardsAboutTiers   @"rewards-about-tiers"
#define EHIScreenAboutPointsScreen   @"about-points"

#define EHIScreenProfile                    @"profile"
#define EHIScreenProfileEditPaymentMethods  @"profile-payment-method-edit"
#define EHIScreenProfileEditPaymentBilling  @"profile-edit-billing"
#define EHIScreenProfileEditPaymentCard     @"profile-edit-card"
#define EHIScreenRemoveBillingModal         @"modal-billing-remove"
#define EHIScreenLocationLockedModal        @"modal-location-locked-modify"

#define EHIScreenProfilePassword    @"password"
#define EHIScreenMemberInfoEdit     @"member-info-edit"
#define EHIScreenLicenseEdit        @"license-edit"
#define EHIScreenPayment            @"payment"
#define EHIScreenPaymentMethod      @"payment-method"
#define EHIScreenSelectPayment      @"select-payment"
#define EHIScreenCardScan           @"card-scan"
#define EHIScreenCustomerSupport    @"customer-support"
#define EHIScreenDebug              @"debug"
#define EHIScreenDebugMap           @"debug-map"

#define EHIScreenPromotionDetails              @"promotion-details"

#define EHIScreenReservation                   @"reservation"
#define EHIScreenReservationItinerary          @"itinerary"
#define EHIScreenReservationAdditionalInfo     @"additional-info"
#define EHIScreenReservationPinAuthentication  @"pin-authentication"
#define EHIScreenReservationCalendar           @"calendar"
#define EHIScreenReservationClassSelect        @"classes"
#define EHIScreenReservationClassSelectFilter  @"class-filter"
#define EHIScreenReservationRateSelect         @"rates"
#define EHIScreenReservationEPlusInfo          @"eplus-info"
#define EHIScreenReservationClassDetails       @"class-details"
#define EHIScreenReservationTimeSelect         @"time-select"
#define EHIScreenReservationExtras             @"extras"
#define EHIScreenReservationFees               @"fees"
#define EHIScreenReservationDriverInfo         @"driver-info"
#define EHIScreenReservationFlightDetails      @"flight-details"
#define EHIScreenReservationAirlineSearch      @"airline-search"
#define EHIScreenReservationReview             @"review"
#define EHIScreenReservationDeliveryCollection @"delivery"
#define EHIScreenReservationRedemption         @"redemption"
#define EHIScreenKeyFacts                      @"key-facts"
#define EHIScreenConfirmationJoin              @"confirmation-join-modal"
